package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategoriePointDeVenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriePointDeVenteAllPropertiesEquals(CategoriePointDeVente expected, CategoriePointDeVente actual) {
        assertCategoriePointDeVenteAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoriePointDeVenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriePointDeVenteAllUpdatablePropertiesEquals(
        CategoriePointDeVente expected,
        CategoriePointDeVente actual
    ) {
        assertCategoriePointDeVenteUpdatableFieldsEquals(expected, actual);
        assertCategoriePointDeVenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriePointDeVenteAutoGeneratedPropertiesEquals(
        CategoriePointDeVente expected,
        CategoriePointDeVente actual
    ) {
        assertThat(actual)
            .as("Verify CategoriePointDeVente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriePointDeVenteUpdatableFieldsEquals(CategoriePointDeVente expected, CategoriePointDeVente actual) {
        assertThat(actual)
            .as("Verify CategoriePointDeVente relevant properties")
            .satisfies(a -> assertThat(a.getCategorie()).as("check categorie").isEqualTo(expected.getCategorie()))
            .satisfies(a -> assertThat(a.getEtablissementRef()).as("check etablissementRef").isEqualTo(expected.getEtablissementRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriePointDeVenteUpdatableRelationshipsEquals(
        CategoriePointDeVente expected,
        CategoriePointDeVente actual
    ) {
        // empty method
    }
}
