package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommissionServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionServiceAllPropertiesEquals(CommissionService expected, CommissionService actual) {
        assertCommissionServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertCommissionServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionServiceAllUpdatablePropertiesEquals(CommissionService expected, CommissionService actual) {
        assertCommissionServiceUpdatableFieldsEquals(expected, actual);
        assertCommissionServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionServiceAutoGeneratedPropertiesEquals(CommissionService expected, CommissionService actual) {
        assertThat(actual)
            .as("Verify CommissionService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionServiceUpdatableFieldsEquals(CommissionService expected, CommissionService actual) {
        assertThat(actual)
            .as("Verify CommissionService relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()))
            .satisfies(a -> assertThat(a.getTypeValue()).as("check typeValue").isEqualTo(expected.getTypeValue()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getEtablissementRef()).as("check etablissementRef").isEqualTo(expected.getEtablissementRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionServiceUpdatableRelationshipsEquals(CommissionService expected, CommissionService actual) {
        // empty method
    }
}
