package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierAllPropertiesEquals(Hier expected, Hier actual) {
        assertHierAutoGeneratedPropertiesEquals(expected, actual);
        assertHierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierAllUpdatablePropertiesEquals(Hier expected, Hier actual) {
        assertHierUpdatableFieldsEquals(expected, actual);
        assertHierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierAutoGeneratedPropertiesEquals(Hier expected, Hier actual) {
        assertThat(actual)
            .as("Verify Hier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierUpdatableFieldsEquals(Hier expected, Hier actual) {
        assertThat(actual)
            .as("Verify Hier relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getParentHierId()).as("check parentHierId").isEqualTo(expected.getParentHierId()))
            .satisfies(a -> assertThat(a.getUnitId()).as("check unitId").isEqualTo(expected.getUnitId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierUpdatableRelationshipsEquals(Hier expected, Hier actual) {
        // empty method
    }
}
