package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModePaiementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementAllPropertiesEquals(ModePaiement expected, ModePaiement actual) {
        assertModePaiementAutoGeneratedPropertiesEquals(expected, actual);
        assertModePaiementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementAllUpdatablePropertiesEquals(ModePaiement expected, ModePaiement actual) {
        assertModePaiementUpdatableFieldsEquals(expected, actual);
        assertModePaiementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementAutoGeneratedPropertiesEquals(ModePaiement expected, ModePaiement actual) {
        assertThat(actual)
            .as("Verify ModePaiement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementUpdatableFieldsEquals(ModePaiement expected, ModePaiement actual) {
        assertThat(actual)
            .as("Verify ModePaiement relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()))
            .satisfies(a -> assertThat(a.getNomMstr()).as("check nomMstr").isEqualTo(expected.getNomMstr()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getEtablissementRef()).as("check etablissementRef").isEqualTo(expected.getEtablissementRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementUpdatableRelationshipsEquals(ModePaiement expected, ModePaiement actual) {
        // empty method
    }
}
