package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RemiseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemiseAllPropertiesEquals(Remise expected, Remise actual) {
        assertRemiseAutoGeneratedPropertiesEquals(expected, actual);
        assertRemiseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemiseAllUpdatablePropertiesEquals(Remise expected, Remise actual) {
        assertRemiseUpdatableFieldsEquals(expected, actual);
        assertRemiseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemiseAutoGeneratedPropertiesEquals(Remise expected, Remise actual) {
        assertThat(actual)
            .as("Verify Remise auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemiseUpdatableFieldsEquals(Remise expected, Remise actual) {
        assertThat(actual)
            .as("Verify Remise relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()))
            .satisfies(a -> assertThat(a.getNomMstr()).as("check nomMstr").isEqualTo(expected.getNomMstr()))
            .satisfies(a -> assertThat(a.getTypeValue()).as("check typeValue").isEqualTo(expected.getTypeValue()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getPointDeVenteRef()).as("check pointDeVenteRef").isEqualTo(expected.getPointDeVenteRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemiseUpdatableRelationshipsEquals(Remise expected, Remise actual) {
        // empty method
    }
}
